export enum AppRoute {
	Home = '/',
	Search = 'search',
	About = 'about',
	AboutHistory = 'about-history',
	AboutCulture = 'about-culture',
	AboutContacts = 'about-contacts',
	Departments = 'departments-list',
	DepartmentsAbout = 'departments-about',
	DepartmentsDetailsHistory = 'departments-details-history',
	DepartmentsDetailsEvents = 'departments-details-events',
	DepartmentsDetailsGallery = 'departments-details-gallery',
	Ethnosport = 'ethnosport',
	Groups = 'groups-list',
	News = 'news',
	Videos = 'videos',
	Events = 'events',
	EventHistory = 'event-history',
	EventGallery = 'event-gallery',
	EventProgram = 'event-program',
	EventInfo = 'event-info',
}
