export enum AppRoute {
	Home = '/',
	Search = 'search',
	About = 'about',
	AboutHistory = 'about-history',
	AboutCulture = 'about-culture',
	AboutContacts = 'about-contacts',
	Objects = 'objects-list',
	News = 'news',
	Videos = 'videos',
	Events = 'events',
	EventHistory = 'event-history',
	EventGallery = 'event-gallery',
	EventProgram = 'event-program',
	EventInfo = 'event-info',
	EventVideos = 'event-videos',
}
